quick analysis of PSPS events from CPUC dashboard

In [2]:
import re
from pathlib import Path

import numpy as np
import pandas as pd

pd.set_option('display.max_columns', 200)
pd.set_option('display.width', 200)

# Clean up accidental quote characters and whitespace in the provided path.
csv_path = Path(str(cpuc_psps_database_file).strip().strip("\"'")).expanduser()
print(f"CSV path: {csv_path}")
print(f"Exists: {csv_path.exists()}")

if not csv_path.exists():
    raise FileNotFoundError(f"Could not find CSV at: {csv_path}")

df_raw = pd.read_csv(csv_path)
print(f"Rows: {len(df_raw):,} | Columns: {len(df_raw.columns)}")
print("Columns:")
print(df_raw.columns.tolist())

df = df_raw.copy()

CSV path: /Users/ryanmc/Documents/Conferences/Jack_Eddy_Symposium_2022/dev/CA_events_data/cpuc_psps_events_dashboard_downloadedJune2026.csv
Exists: True
Rows: 158 | Columns: 26
Columns:
['objectid', 'globalid', 'CreationDate', 'Creator', 'EditDate', 'Editor', 'event_name', 'first_date_of_poc', 'iou', 'de_energization_status', 'de_energization_starting_date', 'full_restoration_date', 'customers_notified', 'customers_de_energized', 'cancelledremoved_from_scope', 'mbl_de_energized', 'counties_de_energized', 'tribes_de_energized', 'transmission_circuits_de_energi', 'distribution_circuits_in_scope', 'distribution_circuits_de_energi', 'damageshazards', 'cfci_de_energized', 'crcccvcrv_open', 'x', 'y']

In [1]:
cpuc_psps_database_file = '/Users/ryanmc/Documents/Conferences/Jack_Eddy_Symposium_2022/dev/CA_events_data/cpuc_psps_events_dashboard_downloadedJune2026.csv'

In [3]:
# Start from a clean copy each run so type conversions are reproducible.
df = df_raw.copy()

# Convert highly numeric object columns to numeric values.
for c in df.columns:
    if pd.api.types.is_object_dtype(df[c]):
        cleaned = df[c].astype(str).str.replace(',', '', regex=False).str.strip()
        as_num = pd.to_numeric(cleaned, errors='coerce')
        if as_num.notna().mean() >= 0.9:
            df[c] = as_num

# Parse only explicit date/time-like columns to datetime.
date_candidates = [c for c in df.columns if re.search(r'date|time', c, re.I)]
for c in date_candidates:
    try:
        df[c] = pd.to_datetime(df[c], errors='coerce')
    except Exception:
        pass

# Create a de-energization duration column in hours when a clear start/end pair exists.
start_col = next((c for c in df.columns if re.search(r'(start|de-?energ.*start)', c, re.I)), None)
end_col = next((c for c in df.columns if re.search(r'(end|restor|re-?energ.*end)', c, re.I)), None)

if start_col and end_col and np.issubdtype(df[start_col].dtype, np.datetime64) and np.issubdtype(df[end_col].dtype, np.datetime64):
    df['deenergization_duration_hours'] = (df[end_col] - df[start_col]).dt.total_seconds() / 3600
    duration_status = f"Computed from '{start_col}' and '{end_col}'"
else:
    duration_status = "Could not infer a clean start/end datetime pair."

print(duration_status)
print()
print("Overall summary (numeric columns):")
display(df.describe(include=[np.number]).T)

print("Overall summary (all columns):")
display(df.describe(include='all').T.head(40))

if 'deenergization_duration_hours' in df.columns:
    dur = df['deenergization_duration_hours'].dropna()
    if len(dur):
        print("De-energization duration statistics (hours):")
        print(dur.describe(percentiles=[0.1, 0.25, 0.5, 0.75, 0.9, 0.95]).round(3))
        neg_count = int((dur < 0).sum())
        if neg_count:
            print(f"Warning: {neg_count} events have negative duration (likely data quality/date parsing issues).")
        print()
        print(f"Longest events (top 10):")
        top_cols = [c for c in [start_col, end_col, 'deenergization_duration_hours', 'event_name', 'iou'] if c in df.columns]
        display(df.sort_values('deenergization_duration_hours', ascending=False)[top_cols].head(10))

Computed from 'de_energization_starting_date' and 'full_restoration_date'

Overall summary (numeric columns):

                                 count          mean            std    min      25%      50%       75%        max
objectid                         158.0    359.746835     486.427925    1.0    42.25     81.5   1119.75     1163.0
customers_notified               158.0  80346.841772  191595.687057    0.0  2768.50  16180.5  71338.25  1615308.0
customers_de_energized           158.0  28347.189873  106221.084694    0.0     0.00    638.0  11552.00   967754.0
cancelledremoved_from_scope       86.0  35805.534884   72076.204029    0.0   831.25   5767.5  39596.00   382720.0
mbl_de_energized                  86.0    463.081395    1483.144674    0.0     0.00     15.0    174.75    11740.0
counties_de_energized             86.0      3.197674       4.629369    0.0     0.00      1.5      4.00       23.0
tribes_de_energized               85.0      1.258824       3.166615    0.0     0.00      0.0      1.00       17.0
transmission_circuits_de_energi   85.0      2.611765      16.522059    0.0     0.00      0.0      0.00      152.0
distribution_circuits_in_scope    86.0     56.255814      97.085309    0.0     3.00     21.0     77.00      619.0
distribution_circuits_de_energi   86.0     20.674419      51.784949    0.0     0.00      2.0     14.50      373.0
damageshazards                    86.0      2.302326       8.453429    0.0     0.00      0.0      1.00       72.0
cfci_de_energized                 86.0    306.872093     885.184073    0.0     0.00     34.0    155.00     6800.0
crcccvcrv_open                    86.0      7.209302       7.872687    0.0     1.00      4.5     11.00       31.0
x                                158.0      0.000000       0.000000    0.0     0.00      0.0      0.00        0.0
y                                158.0      0.000000       0.000000    0.0     0.00      0.0      0.00        0.0
deenergization_duration_hours    116.0     77.379310     123.620362 -649.0    24.00     48.0    102.00      816.0

Overall summary (all columns):

,count,unique,top,freq,mean,min,25%,50%,75%,max,std
objectid,158.0,NaN,NaN,NaN,359.746835,1.0,42.25,81.5,1119.75,1163.0,486.427925
globalid,158,158,78075ed0-4050-4534-8b02-5de6c80c2c86,1,NaN,NaN,NaN,NaN,NaN,NaN,NaN
CreationDate,158,NaN,NaN,NaN,2024-06-09 06:17:46.297468416,2023-11-30 22:01:09,2024-02-13 15:57:11,2024-02-13 17:43:46.500000,2024-11-24 02:53:33.249999872,2026-06-08 21:34:20,NaN
Creator,158,3,mabel.wu_CaPUC,153,NaN,NaN,NaN,NaN,NaN,NaN,NaN
EditDate,158,NaN,NaN,NaN,2024-08-05 11:52:59.392404992,2023-11-30 22:20:53,2024-03-11 21:13:46.249999872,2024-03-11 21:23:20,2024-12-18 22:54:16,2026-06-08 21:34:20,NaN
Editor,158,3,mabel.wu_CaPUC,154,NaN,NaN,NaN,NaN,NaN,NaN,NaN
event_name,158,158,PGE PSPS Event 10/11/21,1,NaN,NaN,NaN,NaN,NaN,NaN,NaN
first_date_of_poc,158,NaN,NaN,NaN,2022-06-11 01:18:36.455696128,2018-01-27 20:00:00,2020-09-06 07:00:00,2021-11-23 08:00:00,2024-11-02 19:45:00,2026-05-17 19:00:00,NaN
iou,158,5,SCE,89,NaN,NaN,NaN,NaN,NaN,NaN,NaN
de_energization_status,158,2,Yes,116,NaN,NaN,NaN,NaN,NaN,NaN,NaN
de_energization_starting_date,116,NaN,NaN,NaN,2022-06-29 19:25:51.724137984,2018-01-27 20:00:00,2020-09-08 13:00:00,2021-10-19 07:00:00,2024-11-15 14:00:00,2026-05-17 19:00:00,NaN
full_restoration_date,116,NaN,NaN,NaN,2022-07-03 00:48:37.241379328,2018-01-29 20:00:00,2020-09-11 13:00:00,2021-10-19 19:00:00,2024-11-15 14:00:00,2026-05-18 19:00:00,NaN
customers_notified,158.0,NaN,NaN,NaN,80346.841772,0.0,2768.5,16180.5,71338.25,1615308.0,191595.687057
customers_de_energized,158.0,NaN,NaN,NaN,28347.189873,0.0,0.0,638.0,11552.0,967754.0,106221.084694
cancelledremoved_from_scope,86.0,NaN,NaN,NaN,35805.534884,0.0,831.25,5767.5,39596.0,382720.0,72076.204029
mbl_de_energized,86.0,NaN,NaN,NaN,463.081395,0.0,0.0,15.0,174.75,11740.0,1483.144674
counties_de_energized,86.0,NaN,NaN,NaN,3.197674,0.0,0.0,1.5,4.0,23.0,4.629369
tribes_de_energized,85.0,NaN,NaN,NaN,1.258824,0.0,0.0,0.0,1.0,17.0,3.166615
transmission_circuits_de_energi,85.0,NaN,NaN,NaN,2.611765,0.0,0.0,0.0,0.0,152.0,16.522059
distribution_circuits_in_scope,86.0,NaN,NaN,NaN,56.255814,0.0,3.0,21.0,77.0,619.0,97.085309
distribution_circuits_de_energi,86.0,NaN,NaN,NaN,20.674419,0.0,0.0,2.0,14.5,373.0,51.784949
damageshazards,86.0,NaN,NaN,NaN,2.302326,0.0,0.0,0.0,1.0,72.0,8.453429
cfci_de_energized,86.0,NaN,NaN,NaN,306.872093,0.0,0.0,34.0,155.0,6800.0,885.184073
crcccvcrv_open,86.0,NaN,NaN,NaN,7.209302,0.0,1.0,4.5,11.0,31.0,7.872687
x,158.0,NaN,NaN,NaN,0.0,0.0,0.0,0.0,0.0,0.0,0.0
y,158.0,NaN,NaN,NaN,0.0,0.0,0.0,0.0,0.0,0.0,0.0
deenergization_duration_hours,116.0,NaN,NaN,NaN,77.37931,-649.0,24.0,48.0,102.0,816.0,123.620362

De-energization duration statistics (hours):
count    116.000
mean      77.379
std      123.620
min     -649.000
10%        0.000
25%       24.000
50%       48.000
75%      102.000
90%      204.500
95%      240.000
max      816.000
Name: deenergization_duration_hours, dtype: float64
Warning: 1 events have negative duration (likely data quality/date parsing issues).

Longest events (top 10):

    de_energization_starting_date full_restoration_date  deenergization_duration_hours                event_name  iou
145           2025-06-18 19:00:00   2025-07-22 19:00:00                          816.0  PG&E PSPS Event 06/19/25  PGE
150           2025-08-10 19:00:00   2025-08-24 19:00:00                          336.0   SCE PSPS Event 08/11/25  SCE
141           2025-01-04 20:00:00   2025-01-17 20:00:00                          312.0   SCE PSPS Event 01/03/25  SCE
144           2025-06-10 19:00:00   2025-06-22 19:00:00                          288.0   SCE PSPS Event 06/10/25  SCE
108           2024-08-08 19:00:00   2024-08-18 19:00:00                          240.0   SCE PSPS Event 08/07/24  SCE
81            2020-12-04 20:00:00   2020-12-14 20:00:00                          240.0   SCE PSPS Event 12/04/20  SCE
48            2019-10-02 19:00:00   2019-10-12 19:00:00                          240.0   SCE PSPS Event 10/02/19  SCE
47            2019-09-21 19:00:00   2019-10-01 19:00:00                          240.0   SCE PSPS Event 09/21/19  SCE
46            2019-09-09 19:00:00   2019-09-19 19:00:00                          240.0   SCE PSPS Event 09/09/19  SCE
146           2025-07-01 19:00:00   2025-07-11 19:00:00                          240.0   SCE PSPS Event 06/30/25  SCE

In [15]:
df[df['deenergization_duration_hours']<0] #.sort_values('deenergization_duration_hours', ascending=False)

,objectid,globalid,CreationDate,Creator,EditDate,Editor,event_name,first_date_of_poc,iou,de_energization_status,de_energization_starting_date,full_restoration_date,customers_notified,customers_de_energized,cancelledremoved_from_scope,mbl_de_energized,counties_de_energized,tribes_de_energized,transmission_circuits_de_energi,distribution_circuits_in_scope,distribution_circuits_de_energi,damageshazards,cfci_de_energized,crcccvcrv_open,x,y,deenergization_duration_hours
78,81,cb349076-cd33-430a-8f17-56b2809ca225,2024-02-13 17:43:17,mabel.wu_CaPUC,2024-03-11 21:21:23,mabel.wu_CaPUC,SCE PSPS Event 11/14/20,2020-11-14 20:00:00,SCE,Yes,2020-11-14 20:00:00,2020-10-18 19:00:00,10402,509,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0,0,-649.0

In [4]:
# Identify likely geography and hazard columns.
area_candidates = [c for c in df.columns if re.search(r'county|city|community|district|zip|area|region|circuit', c, re.I)]
hazard_candidates = [c for c in df.columns if re.search(r'hazard|weather|wind|fire|storm|heat|rain|snow|lightning', c, re.I)]

print("Likely area columns:", area_candidates)
print("Likely hazard columns:", hazard_candidates)
print()

# High-level insights requested.
if 'de_energization_status' in df.columns:
    de_yes = (df['de_energization_status'].astype(str).str.strip().str.lower() == 'yes').sum()
    print(f"Events with actual de-energization: {de_yes}/{len(df)} ({de_yes/len(df):.1%})")

if 'damageshazards' in df.columns:
    hazard_events = (df['damageshazards'].fillna(0) > 0).sum()
    print(f"Events with >0 damages/hazards: {hazard_events}/{len(df)} ({hazard_events/len(df):.1%})")

if 'iou' in df.columns:
    print("Event counts by IOU:")
    display(df['iou'].value_counts(dropna=False).to_frame('event_count'))

if 'de_energization_starting_date' in df.columns and pd.api.types.is_datetime64_any_dtype(df['de_energization_starting_date']):
    yearly = df['de_energization_starting_date'].dt.year.value_counts().sort_index()
    print("De-energization starts by year:")
    display(yearly.to_frame('event_count'))

if 'counties_de_energized' in df.columns:
    print("Top events by number of counties de-energized:")
    cols = [c for c in ['event_name', 'iou', 'counties_de_energized', 'deenergization_duration_hours'] if c in df.columns]
    display(df.sort_values('counties_de_energized', ascending=False)[cols].head(10))
print()

for c in area_candidates[:5]:
    vc = df[c].astype(str).str.strip().replace({'': np.nan}).dropna().value_counts().head(15)
    print(f"Most frequently affected values in '{c}':")
    display(vc.to_frame('event_count'))
    print()

for c in hazard_candidates[:5]:
    vc = df[c].astype(str).str.strip().replace({'': np.nan}).dropna().value_counts().head(20)
    print(f"Hazard distribution in '{c}':")
    display(vc.to_frame('event_count'))
    print()

# Column relationship scan: numeric correlations and duration-by-category patterns.
num_cols = [c for c in df.columns if pd.api.types.is_numeric_dtype(df[c])]
if len(num_cols) >= 2:
    corr = df[num_cols].corr(numeric_only=True)
    print("Top absolute numeric correlations:")
    corr_pairs = (
        corr.where(~np.eye(corr.shape[0], dtype=bool))
            .stack()
            .rename('corr')
            .abs()
            .sort_values(ascending=False)
            .head(20)
    )
    display(corr_pairs.to_frame())
    print()

if 'deenergization_duration_hours' in df.columns and len(area_candidates):
    c = area_candidates[0]
    tmp = df[[c, 'deenergization_duration_hours']].dropna()
    if len(tmp):
        grouped = tmp.groupby(c)['deenergization_duration_hours'].agg(['count', 'mean', 'median', 'max']).sort_values('count', ascending=False).head(20)
        print(f"Duration statistics by '{c}' (top 20 by event count):")
        display(grouped)
        print()

print("Missingness (% by column):")
missing_pct = (df.isna().mean() * 100).sort_values(ascending=False).round(2)
display(missing_pct.to_frame('missing_pct'))

Likely area columns: ['transmission_circuits_de_energi', 'distribution_circuits_in_scope', 'distribution_circuits_de_energi']
Likely hazard columns: ['damageshazards']

Events with actual de-energization: 116/158 (73.4%)
Events with >0 damages/hazards: 28/158 (17.7%)
Event counts by IOU:

                   event_count
iou
SCE                         89
PGE                         38
SDGE                        20
Liberty Utilities            8
PacifiCorp                   3

De-energization starts by year:

                               event_count
de_energization_starting_date
2018.0                                   6
2019.0                                  20
2020.0                                  21
2021.0                                  15
2022.0                                   3
2023.0                                   7
2024.0                                  23
2025.0                                  20
2026.0                                   1

Top events by number of counties de-energized:

                     event_name  iou  counties_de_energized  deenergization_duration_hours
0       PGE PSPS Event 10/11/21  PGE                   23.0                           24.0
115    PG&E PSPS Event 10/17/24  PGE                   21.0                           72.0
145    PG&E PSPS Event 06/19/25  PGE                   19.0                          816.0
118    PG&E PSPS Event 11/05/24  PGE                   17.0                           72.0
157  PG&E PSPS Event 05/17/2026  PGE                   15.0                           24.0
150     SCE PSPS Event 08/11/25  SCE                    8.0                          336.0
141     SCE PSPS Event 01/03/25  SCE                    8.0                          312.0
125     SCE PSPS Event 11/04/24  SCE                    8.0                           96.0
103    PG&E PSPS Event 07/02/24  PGE                    8.0                           24.0
19     PG&E PSPS Event 08/30/23  PGE                    7.0                           24.0

Most frequently affected values in 'transmission_circuits_de_energi':

                                 event_count
transmission_circuits_de_energi
nan                                       73
0.0                                       68
3.0                                        5
4.0                                        4
5.0                                        2
1.0                                        2
152.0                                      1
10.0                                       1
8.0                                        1
9.0                                        1

Most frequently affected values in 'distribution_circuits_in_scope':

                                event_count
distribution_circuits_in_scope
nan                                      72
2.0                                      13
1.0                                       7
3.0                                       4
10.0                                      3
5.0                                       3
31.0                                      3
33.0                                      2
12.0                                      2
77.0                                      2
14.0                                      2
133.0                                     2
23.0                                      2
79.0                                      2
447.0                                     1

Most frequently affected values in 'distribution_circuits_de_energi':

                                 event_count
distribution_circuits_de_energi
nan                                       72
0.0                                       24
2.0                                       13
1.0                                        8
4.0                                        4
6.0                                        4
3.0                                        3
5.0                                        2
20.0                                       2
97.0                                       2
7.0                                        2
31.0                                       2
13.0                                       2
225.0                                      1
33.0                                       1

Hazard distribution in 'damageshazards':

                event_count
damageshazards
nan                      72
0.0                      58
1.0                       9
3.0                       6
2.0                       3
8.0                       2
4.0                       2
11.0                      2
10.0                      1
12.0                      1
72.0                      1
25.0                      1

Top absolute numeric correlations:

                                                                     corr
cfci_de_energized               mbl_de_energized                 0.988364
mbl_de_energized                cfci_de_energized                0.988364
cfci_de_energized               customers_de_energized           0.984775
customers_de_energized          cfci_de_energized                0.984775
                                mbl_de_energized                 0.981295
mbl_de_energized                customers_de_energized           0.981295
distribution_circuits_in_scope  customers_notified               0.977034
customers_notified              distribution_circuits_in_scope   0.977034
cancelledremoved_from_scope     customers_notified               0.974905
customers_notified              cancelledremoved_from_scope      0.974905
damageshazards                  customers_de_energized           0.967889
customers_de_energized          damageshazards                   0.967889
cfci_de_energized               distribution_circuits_de_energi  0.964863
distribution_circuits_de_energi cfci_de_energized                0.964863
damageshazards                  mbl_de_energized                 0.959526
mbl_de_energized                damageshazards                   0.959526
cancelledremoved_from_scope     distribution_circuits_in_scope   0.959493
distribution_circuits_in_scope  cancelledremoved_from_scope      0.959493
distribution_circuits_de_energi mbl_de_energized                 0.957840
mbl_de_energized                distribution_circuits_de_energi  0.957840

Duration statistics by 'transmission_circuits_de_energi' (top 20 by event count):

                                 count        mean  median    max
transmission_circuits_de_energi
0.0                                 45   57.066667    24.0  336.0
3.0                                  5   72.000000    24.0  216.0
4.0                                  4  114.000000    60.0  312.0
1.0                                  2  228.000000   228.0  288.0
5.0                                  2   48.000000    48.0   72.0
8.0                                  1   96.000000    96.0   96.0
9.0                                  1  816.000000   816.0  816.0
10.0                                 1   48.000000    48.0   48.0
152.0                                1   24.000000    24.0   24.0

Missingness (% by column):

                                 missing_pct
transmission_circuits_de_energi        46.20
tribes_de_energized                    46.20
mbl_de_energized                       45.57
crcccvcrv_open                         45.57
cfci_de_energized                      45.57
damageshazards                         45.57
distribution_circuits_de_energi        45.57
distribution_circuits_in_scope         45.57
counties_de_energized                  45.57
cancelledremoved_from_scope            45.57
deenergization_duration_hours          26.58
de_energization_starting_date          26.58
full_restoration_date                  26.58
y                                       0.00
x                                       0.00
objectid                                0.00
globalid                                0.00
customers_notified                      0.00
de_energization_status                  0.00
iou                                     0.00
first_date_of_poc                       0.00
event_name                              0.00
Editor                                  0.00
EditDate                                0.00
Creator                                 0.00
CreationDate                            0.00
customers_de_energized                  0.00

In [7]:
cwd = Path.cwd()
output_dir = (cwd / 'outputs') if cwd.name == 'notebooks' else (cwd / 'notebooks' / 'outputs')
output_dir.mkdir(parents=True, exist_ok=True)
output_path = output_dir / 'cpuc_psps_statistical_analysis.xlsx'


def to_export_frame(obj, index_name=None):
    if isinstance(obj, pd.Series):
        frame = obj.to_frame(name='value')
    else:
        frame = obj.copy()
    if index_name and frame.index.name is None:
        frame.index.name = index_name
    return frame


def add_table(tables, sheet_name, description, data, index_name=None):
    frame = to_export_frame(data, index_name=index_name)
    if frame.empty:
        return
    tables.append(
        {
            'sheet_name': sheet_name,
            'description': description,
            'data': frame,
        }
    )


def make_sheet_name(name, used_names):
    cleaned = re.sub(r'[\\/*?:\[\]]', '_', name).strip() or 'Sheet'
    cleaned = cleaned[:31]
    candidate = cleaned
    counter = 1
    while candidate in used_names:
        suffix = f'_{counter}'
        candidate = f"{cleaned[:31 - len(suffix)]}{suffix}"
        counter += 1
    used_names.add(candidate)
    return candidate


tables_to_export = []

numeric_summary = df.describe(include=[np.number]).T
add_table(
    tables_to_export,
    'numeric_summary',
    'Summary statistics for all numeric CPUC PSPS columns.',
    numeric_summary,
    index_name='column',
)

all_summary = df.describe(include='all').T.head(40)
add_table(
    tables_to_export,
    'all_columns_summary',
    'First 40 rows of the full descriptive summary across all column types.',
    all_summary,
    index_name='column',
)

if 'deenergization_duration_hours' in df.columns:
    dur = df['deenergization_duration_hours'].dropna()
    if len(dur):
        duration_stats = dur.describe(percentiles=[0.1, 0.25, 0.5, 0.75, 0.9, 0.95]).round(3)
        add_table(
            tables_to_export,
            'duration_stats',
            'Distribution summary for de-energization duration in hours.',
            duration_stats,
            index_name='statistic',
        )

        top_cols = [c for c in [start_col, end_col, 'deenergization_duration_hours', 'event_name', 'iou'] if c in df.columns]
        longest_events = df.sort_values('deenergization_duration_hours', ascending=False)[top_cols].head(10)
        add_table(
            tables_to_export,
            'longest_events',
            'Ten longest PSPS events ranked by computed de-energization duration.',
            longest_events,
        )

if 'de_energization_status' in df.columns:
    de_mask = df['de_energization_status'].astype(str).str.strip().str.lower() == 'yes'
    de_status_summary = pd.DataFrame(
        {
            'metric': ['actual_deenergization_events', 'total_events', 'share_actual_deenergization'],
            'value': [int(de_mask.sum()), int(len(df)), float(de_mask.mean())],
        }
    )
    add_table(
        tables_to_export,
        'deenergization_status',
        'Counts and share of events with an actual de-energization status of yes.',
        de_status_summary,
    )

if 'damageshazards' in df.columns:
    hazard_mask = df['damageshazards'].fillna(0) > 0
    hazard_summary = pd.DataFrame(
        {
            'metric': ['events_with_positive_damageshazards', 'total_events', 'share_with_positive_damageshazards'],
            'value': [int(hazard_mask.sum()), int(len(df)), float(hazard_mask.mean())],
        }
    )
    add_table(
        tables_to_export,
        'hazard_event_summary',
        'Counts and share of events with damages or hazards greater than zero.',
        hazard_summary,
    )

if 'iou' in df.columns:
    iou_counts = df['iou'].value_counts(dropna=False).to_frame('event_count')
    add_table(
        tables_to_export,
        'iou_event_counts',
        'Event counts grouped by investor-owned utility.',
        iou_counts,
        index_name='iou',
    )

if 'de_energization_starting_date' in df.columns and pd.api.types.is_datetime64_any_dtype(df['de_energization_starting_date']):
    yearly = df['de_energization_starting_date'].dt.year.value_counts().sort_index().to_frame('event_count')
    add_table(
        tables_to_export,
        'events_by_year',
        'Event counts by de-energization starting year.',
        yearly,
        index_name='year',
    )

if 'counties_de_energized' in df.columns:
    cols = [c for c in ['event_name', 'iou', 'counties_de_energized', 'deenergization_duration_hours'] if c in df.columns]
    top_county_events = df.sort_values('counties_de_energized', ascending=False)[cols].head(10)
    add_table(
        tables_to_export,
        'top_county_events',
        'Ten events with the highest number of counties de-energized.',
        top_county_events,
    )

for idx, c in enumerate(area_candidates[:5], start=1):
    vc = df[c].astype(str).str.strip().replace({'': np.nan}).dropna().value_counts().head(15)
    add_table(
        tables_to_export,
        f'area_distribution_{idx}',
        f"Top 15 most frequent values observed in the '{c}' area-related column.",
        vc.to_frame('event_count'),
        index_name=c,
    )

for idx, c in enumerate(hazard_candidates[:5], start=1):
    vc = df[c].astype(str).str.strip().replace({'': np.nan}).dropna().value_counts().head(20)
    add_table(
        tables_to_export,
        f'hazard_distribution_{idx}',
        f"Top 20 value counts observed in the '{c}' hazard-related column.",
        vc.to_frame('event_count'),
        index_name=c,
    )

num_cols = [c for c in df.columns if pd.api.types.is_numeric_dtype(df[c])]
if len(num_cols) >= 2:
    corr = df[num_cols].corr(numeric_only=True)
    corr_pairs = (
        corr.where(~np.eye(corr.shape[0], dtype=bool))
        .stack()
        .rename('corr')
        .abs()
        .sort_values(ascending=False)
        .head(20)
        .reset_index()
        .rename(columns={'level_0': 'variable_1', 'level_1': 'variable_2'})
    )
    add_table(
        tables_to_export,
        'top_correlations',
        'Top 20 absolute pairwise correlations among numeric columns.',
        corr_pairs,
    )

if 'deenergization_duration_hours' in df.columns and len(area_candidates):
    c = area_candidates[0]
    tmp = df[[c, 'deenergization_duration_hours']].dropna()
    if len(tmp):
        grouped = (
            tmp.groupby(c)['deenergization_duration_hours']
            .agg(['count', 'mean', 'median', 'max'])
            .sort_values('count', ascending=False)
            .head(20)
        )
        add_table(
            tables_to_export,
            'duration_by_area',
            f"Duration statistics grouped by the leading area candidate column '{c}'.",
            grouped,
            index_name=c,
        )

missing_pct = (df.isna().mean() * 100).sort_values(ascending=False).round(2).to_frame('missing_pct')
add_table(
    tables_to_export,
    'missingness',
    'Missing-value percentage for each column in the CPUC PSPS dataset.',
    missing_pct,
    index_name='column',
)

sheet_descriptions = []
used_sheet_names = set()
with pd.ExcelWriter(output_path) as writer:
    for item in tables_to_export:
        sheet_name = make_sheet_name(item['sheet_name'], used_sheet_names)
        item['data'].to_excel(writer, sheet_name=sheet_name, startrow=2)
        worksheet = writer.sheets[sheet_name]
        worksheet.cell(row=1, column=1, value='Description')
        worksheet.cell(row=1, column=2, value=item['description'])
        sheet_descriptions.append({'sheet_name': sheet_name, 'description': item['description']})

print(f'Exported {len(sheet_descriptions)} tables to {output_path}')
display(pd.DataFrame(sheet_descriptions))

Exported 16 tables to /Users/ryanmc/Documents/Complex_Risk_Science/dev/Complex-Risk-Collective/.github/Projects/NASA-disasters-grid-resilience/notebooks/outputs/cpuc_psps_statistical_analysis.xlsx

               sheet_name                                        description
0         numeric_summary  Summary statistics for all numeric CPUC PSPS c...
1     all_columns_summary  First 40 rows of the full descriptive summary ...
2          duration_stats  Distribution summary for de-energization durat...
3          longest_events  Ten longest PSPS events ranked by computed de-...
4   deenergization_status  Counts and share of events with an actual de-e...
5    hazard_event_summary  Counts and share of events with damages or haz...
6        iou_event_counts    Event counts grouped by investor-owned utility.
7          events_by_year     Event counts by de-energization starting year.
8       top_county_events  Ten events with the highest number of counties...
9     area_distribution_1  Top 15 most frequent values observed in the 't...
10    area_distribution_2  Top 15 most frequent values observed in the 'd...
11    area_distribution_3  Top 15 most frequent values observed in the 'd...
12  hazard_distribution_1  Top 20 value counts observed in the 'damagesha...
13       top_correlations  Top 20 absolute pairwise correlations among nu...
14       duration_by_area  Duration statistics grouped by the leading are...
15            missingness  Missing-value percentage for each column in th...